### ISSUE TITLE
Test Diagnostics 

### ISSUE THREAD

**Issue by tarankalra1** [tarankalra/COAWST_VEG#5]
Switching on UV_Diagnostics makes the code crash

**Comment by alexisbeudin** [comment]
ok, can you take care of this issue?

----- Mail original -----
De: "Tarandeep Singh Kalra" notifications@github.com
À: "tarankalra/COAWST_VEG" COAWST_VEG@noreply.github.com
Envoyé: Jeudi 10 Septembre 2015 15:14:03
Objet: [COAWST_VEG] Test Diagnostics  (#5)

Switching on UV_Diagnostics makes the code crash
